#!/bin/bash

source ./FLASH_CONFIG.CONF

DEV_BOARD=`cat $BUILDROOT_DIRECTORY/.config | grep BR2_PACKAGE_HART_SOFTWARE_SERVICES_BOARD | sed 's/BR2_PACKAGE_HART_SOFTWARE_SERVICES_BOARD=//g' | sed 's/"//g'`
DEV_DIE=`cat $BUILDROOT_DIRECTORY/.config | grep BR2_PACKAGE_HART_SOFTWARE_SERVICES_DIE | sed 's/BR2_PACKAGE_HART_SOFTWARE_SERVICES_DIE=//g' | sed 's/"//g'`
DEV_PACKAGE=`cat $BUILDROOT_DIRECTORY/.config | grep BR2_PACKAGE_HART_SOFTWARE_SERVICES_PACKAGE | sed 's/BR2_PACKAGE_HART_SOFTWARE_SERVICES_PACKAGE=//g' | sed 's/"//g'`

echo
echo "BOARD is set to $DEV_BOARD"
echo "DIE is set to $DEV_DIE"
echo "PACKAGE is set to $DEV_PACKAGE"
echo

make -C $BUILDROOT_DIRECTORY/output/build/hart-software-services-next program BOARD=$DEV_BOARD DIE=$DEV_DIE PACKAGE=$DEV_PACKAGE
